import Head from 'next/head'
import Body from '../components/body'
import Footer from '../components/footer'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        < Body/>
      </main>
        <Footer/>
      
    </div>
  )
}
